#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : sysfsutils
Version  : 2.1.0
Release  : 4
URL      : https://downloads.sourceforge.net/linux-diag/sysfsutils-2.1.0.tar.gz
Source0  : https://downloads.sourceforge.net/linux-diag/sysfsutils-2.1.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: sysfsutils-bin
Requires: sysfsutils-lib
Requires: sysfsutils-doc

%description
Sysfs Utilities Package - Includes Libsysfs(v. 2.1.0)
======================================================

%package bin
Summary: bin components for the sysfsutils package.
Group: Binaries

%description bin
bin components for the sysfsutils package.


%package dev
Summary: dev components for the sysfsutils package.
Group: Development
Requires: sysfsutils-lib
Requires: sysfsutils-bin

%description dev
dev components for the sysfsutils package.


%package doc
Summary: doc components for the sysfsutils package.
Group: Documentation

%description doc
doc components for the sysfsutils package.


%package lib
Summary: lib components for the sysfsutils package.
Group: Libraries

%description lib
lib components for the sysfsutils package.


%prep
%setup -q -n sysfsutils-2.1.0

%build
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=intel.com,localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/dlist_test
/usr/bin/get_device
/usr/bin/get_driver
/usr/bin/get_module
/usr/bin/systool

%files dev
%defattr(-,root,root,-)
/usr/include/sysfs/dlist.h
/usr/include/sysfs/libsysfs.h
/usr/lib64/*.so

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
